# render.yaml - Versión 5.0 (Basada en la Documentación)

databases:
  - name: gm-postgres
    plan: free
    databaseName: gm_main_db
    user: gm_user

services:
  # --- Servicios Privados (no accesibles desde fuera) ---
  - name: gm-rabbitmq
    type: web
    runtime: image # SOLUCIÓN 1: Especifica que estamos usando una imagen preconstruida
    plan: free
    image:
      url: rabbitmq:3.13-management-alpine

  - name: gm-chromadb
    type: web
    runtime: image # SOLUCIÓN 1: Especifica que estamos usando una imagen preconstruida
    plan: free
    image:
      url: chromadb/chroma:0.4.24

  # --- Servicio Web Principal ---
  - name: gm-auth-game-service
    type: web
    plan: free
    runtime: docker
    dockerfilePath: ./auth_game_service/Dockerfile
    dockerContext: ./auth_game_service
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gm-postgres
          property: connectionString
      # SOLUCIÓN 2 y 3: Construimos la URL de RabbitMQ manualmente
      - key: RABBITMQ_URL
        value: amqp://${gm-secrets.RABBITMQ_DEFAULT_USER}:${gm-secrets.RABBITMQ_DEFAULT_PASS}@${gm-rabbitmq.host}:5672/
      - fromGroup: gm-secrets

  # --- Trabajador de Fondo ---
  - name: gm-worker
    type: worker
    plan: free
    runtime: docker
    dockerfilePath: ./gm_worker/Dockerfile
    dockerContext: ./gm_worker
    # SOLUCIÓN 4: Cambiado 'startCommand' a 'dockerCommand'
    dockerCommand: celery -A app.worker.celery_app worker -P eventlet -Q gm_tasks --concurrency=10 --loglevel=info
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gm-postgres
          property: connectionString

      - key: RABBITMQ_URL
        value: amqp://${gm-secrets.RABBITMQ_DEFAULT_USER}:${gm-secrets.RABBITMQ_DEFAULT_PASS}@${gm-rabbitmq.host}:5672/
      - key: CHROMADB_HOST
        fromService:
          type: web
          name: gm-chromadb
          property: host
      - key: CHROMADB_PORT
        fromService:
          type: web
          name: gm-chromadb
          property: port
      - fromGroup: gm-secrets

# --- Grupo de Variables de Entorno Secretas ---
envVarGroups:
  - name: gm-secrets
    envVars:
      - key: GEMINI_API_KEY
        value: "YOUR_GEMINI_API_KEY_HERE"
      - key: RABBITMQ_DEFAULT_USER
        generateValue: true
      - key: RABBITMQ_DEFAULT_PASS
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: JWT_ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30