# render.yaml - v7.1 - Añadido comando de arranque para el servicio web

databases:
  - name: gm-postgres
    plan: free
    databaseName: gm_main_db
    user: gm_user

services:
  - name: gm-rabbitmq
    type: web
    runtime: image
    plan: free
    image:
      url: rabbitmq:3.13-management-alpine

  - name: gm-chromadb
    type: web
    runtime: image
    plan: free
    image:
      url: chromadb/chroma:0.4.24

  # --- SERVICIO WEB PRINCIPAL ---
  - name: gm-auth-game-service
    type: web
    plan: free
    runtime: docker
    dockerfilePath: ./auth_game_service/Dockerfile
    dockerContext: ./auth_game_service
    # --- INICIO DE LÍNEAS NUEVAS ---
    # Le decimos a Render cómo arrancar Uvicorn.
    # Usamos $PORT para que sea compatible con la red de Render.
    dockerCommand: uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8001}
    # --- FIN DE LÍNEAS NUEVAS ---
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gm-postgres
          property: connectionString
      - key: RABBITMQ_URL
        value: amqp://${gm-secrets.RABBITMQ_DEFAULT_USER}:${gm-secrets.RABBITMQ_DEFAULT_PASS}@${gm-rabbitmq.host}:5672/
      - fromGroup: gm-secrets

  # --- TRABAJADOR DE FONDO (CONVERTIDO A WEB SERVICE) ---
  - name: gm-worker
    type: web
    plan: free
    runtime: docker
    dockerfilePath: ./gm_worker/Dockerfile
    dockerContext: ./gm_worker
    dockerCommand: ./start.sh
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gm-postgres
          property: connectionString
      - key: RABBITMQ_URL
        value: amqp://${gm-secrets.RABBITMQ_DEFAULT_USER}:${gm-secrets.RABBITMQ_DEFAULT_PASS}@${gm-rabbitmq.host}:5672/
      - key: CHROMADB_HOST
        fromService:
          type: web
          name: gm-chromadb
          property: host
      - key: CHROMADB_PORT
        fromService:
          type: web
          name: gm-chromadb
          property: port
      - fromGroup: gm-secrets

envVarGroups:
  - name: gm-secrets
    envVars:
      - key: GEMINI_API_KEY
        value: "YOUR_GEMINI_API_KEY_HERE"
      - key: RABBITMQ_DEFAULT_USER
        generateValue: true
      - key: RABBITMQ_DEFAULT_PASS
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: JWT_ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30